<a href="https://colab.research.google.com/github/shubhamL2477/AI-SEM3/blob/main/workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: shubham shrestha
Group : 11
Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.



1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
arr_empty = np.empty((2,2))
print(arr_empty)

[[4.09697049e-315 0.00000000e+000]
 [4.94065646e-324 6.53248276e-310]]


2. Initialize an all one array with size 4X2.

In [ ]:
arr_ones = np.ones((4,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
arr_full = np.full((3,3), 11)
print(arr_full);

[[11 11 11]
 [11 11 11]
 [11 11 11]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
a = np.array([[3,4,5],[6,7,8]])
zeros_like = np.zeros_like(a)
print(zeros_like)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like = np.ones_like(a)
print(ones_like)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
new_np_array = np.array(new_list)
print(new_np_array)

[1 2 3 4]


Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()
print(rand_arr)
print(mean_val)

[0.47408567 0.26833273 0.174458   0.44661848 0.54613581 0.70760107
 0.41123345 0.63716001 0.59005501 0.82403128 0.92887418 0.58038151
 0.783303   0.54856134 0.46917981 0.01309734 0.41640654 0.33704027
 0.44343458 0.99364871 0.17327061 0.44617278 0.1446456  0.85219963
 0.95954439 0.66993257 0.32287919 0.81378495 0.20960788 0.62120143]
0.5268959277267379


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
r10 = np.random.random((10,10))
min_val = r10.min()
max_val = r10.max()
print(r10)
print("the minimum value is = ",min_val)
print("the maximum value is = ",max_val)

[[0.58753957 0.71073947 0.23682535 0.55452051 0.43809712 0.14004459
  0.5035081  0.9290349  0.41721992 0.4684733 ]
 [0.74103738 0.26529608 0.32449406 0.08666598 0.38730101 0.04105437
  0.60502721 0.57186754 0.72971191 0.39435526]
 [0.22680669 0.40910965 0.73199986 0.42915145 0.5346105  0.24281329
  0.46128405 0.06480278 0.14739732 0.8957852 ]
 [0.76235427 0.72210467 0.41108632 0.91553767 0.44418436 0.50914702
  0.98836817 0.21402948 0.82196197 0.04741201]
 [0.93481553 0.81440371 0.03702876 0.38804646 0.07016564 0.37370963
  0.80965761 0.67119419 0.72160888 0.116383  ]
 [0.82395985 0.41238617 0.26753865 0.86359865 0.77988599 0.85119753
  0.04677675 0.64075038 0.92894974 0.7233185 ]
 [0.08524283 0.76344118 0.56464141 0.56063202 0.47699773 0.88245179
  0.87782102 0.66679485 0.70514495 0.56727215]
 [0.40592176 0.79795046 0.75230876 0.48347626 0.57506817 0.74262788
  0.35945692 0.31780982 0.54239432 0.18805252]
 [0.36936909 0.02491586 0.75470712 0.00957391 0.81749168 0.59060218
  0.83164871

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr_rev = np.array([1,2,0,0,4,0])[::-1]
print(arr_rev)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
square = np.ones((5,5))
square[1:-1,1:-1] = 0
print(square)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Array Operations

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add = x + y
print(add)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
sub = x - y
print(sub)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
mul_int = x * 3
print(mul_int)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
squared = x**2
print(squared)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
d1 = np.dot(v,w)
d2 = np.dot(x,v)
d3 = np.dot(x,y)
print(d1)
print()
print(d2)
print()
print(d3)


219

[29 77]

[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
concat_xy = np.vstack((x,y))
concat_vw = np.column_stack((v,w))
print(concat_xy)
print()
print(concat_vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    result = np.concatenate((x,v))
except Exception as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Ans : all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Matrix Operations

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

1) Prove A.A−1 = I.

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


A_inv = np.linalg.inv(A)
I = A @ A_inv
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB ≠ BA:", not np.array_equal(AB, BA))


AB ≠ BA: True


3. Prove (AB)

T = BTAT
# .

In [ ]:
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_T, BT_AT))

(AB)ᵀ = BᵀAᵀ: True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")

x = 2.0, y = 1.0, z = -2.0


How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np


size = 1000000
list1 = list(range(size))
list2 = list(range(size, size*2))
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")
arr1 = np.arange(size)
arr2 = np.arange(size, size*2)

start = time.time()
result_np = arr1 + arr2
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: 0.1346 seconds
NumPy arrays: 0.0064 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")

start = time.time()
result_np = arr1 * arr2
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: 0.2513 seconds
NumPy arrays: 0.0043 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")


Python lists: 0.2315 seconds
NumPy arrays: 0.0026 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
size_mat = 1000
matrix1 = [[1]*size_mat for _ in range(size_mat)]
matrix2 = [[1]*size_mat for _ in range(size_mat)]

start = time.time()

result = [[0]*size_mat for _ in range(size_mat)]
end = time.time()
print(f"Python lists: >{end-start:.4f} seconds (too slow to implement fully)")

np_matrix1 = np.ones((size_mat, size_mat))
np_matrix2 = np.ones((size_mat, size_mat))

start = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: >0.0086 seconds (too slow to implement fully)
NumPy arrays: 0.0678 seconds
